export enum Banned {
  Conjure = 'CONJURE',
  Consume = 'CONSUME',
  Contraption = 'CONTRAPTION',
  DamageSleeves = 'DAMAGE_SLEEVES',
  DeckSize100 = 'DECK_SIZE_100',
  Dexterity = 'DEXTERITY',
  Host = 'HOST',
  KamigawaCost = 'KAMIGAWA_COST',
  Kidney = 'KIDNEY',
  Outside = 'OUTSIDE',
  Perpetual = 'PERPETUAL',
  Racism = 'RACISM',
  RandomCreature = 'RANDOM_CREATURE',
  RemoveSleeves = 'REMOVE_SLEEVES',
  Seek = 'SEEK',
  Specialize = 'SPECIALIZE',
  Time = 'TIME',
  Toys = 'TOYS',
  Unfun = 'UNFUN',
  VisualAccessibility = 'VISUAL_ACCESSIBILITY',
}
